# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VecToYOLO
                                 A QGIS plugin
 This plugin generates image chips for YOLO training
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        copyright            : (C) 2026 by Yogi Satrio Wijoyo
        email                : s.wyogi32@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yogi Satrio Wijoyo'
__date__ = '2026-03-02'
__copyright__ = '(C) 2026 by Yogi Satrio Wijoyo'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VecToYOLO class from file VecToYOLO.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vec_to_yolo import VecToYOLOPlugin
    return VecToYOLOPlugin(iface)
