# -*- coding: utf-8 -*-

"""
/***************************************************************************
 VecToYOLO
                                 A QGIS plugin
 This plugin generates image chips for YOLO training
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        copyright            : (C) 2026 by Yogi Satrio Wijoyo
        email                : s.wyogi32@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yogi Satrio Wijoyo'
__date__ = '2026-03-02'
__copyright__ = '(C) 2026 by Yogi Satrio Wijoyo'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import (QCoreApplication, QVariant)
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingUtils,
                       QgsProcessingParameterExtent,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFolderDestination,
                       QgsField,
                       QgsProcessingParameterEnum,
                       QgsRectangle,
                       QgsFeatureRequest,
                       QgsSpatialIndex
                       )
from qgis import processing
import math
import numpy as np
from osgeo import gdal
import os
import cv2
import random
import yaml


class VecToYOLOAlgorithm(QgsProcessingAlgorithm):
    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterExtent(
                'MAP_EXTENT',
                self.tr('Map Extent'),
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                'INPUT_RASTER',
                self.tr('Input Raster'),
            )
        )
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                'INPUT_VECTOR',
                self.tr('Input Vector Layer'),
            )
        )
        self.addParameter(
            QgsProcessingParameterField(
                'CLASS_FIELD',
                self.tr('Class Field'),
                parentLayerParameterName = 'INPUT_VECTOR'
            )
        )
        
        self.addParameter(
            QgsProcessingParameterEnum(
                'TASK',
                self.tr('Task'),
                options=['Detection', 'Segmentation'],
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                'OVERLAP',
                self.tr('Overlap (%) — Recommended 0% for landcover dataset'),
                type = QgsProcessingParameterNumber.Integer,
                defaultValue = 15
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                'CHIP_SIZE',
                self.tr('Chip Size'),
                type = QgsProcessingParameterNumber.Integer,
                defaultValue = 640
            )
        )
        
        self.addParameter(
             QgsProcessingParameterEnum(
                'DATA_SOURCE',
                self.tr('Data Source'),
                options=['Satellite Imagery (16-bit)', 'Drone Orthomosaic (8-bit)'],
                defaultValue=0
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                'MAX_REFLECTANCE',
                self.tr('Maximum Reflectance (Scaling Factor) — For 16-bit Satellite Imagery'),
                type = QgsProcessingParameterNumber.Integer,
                defaultValue = 10000,
                minValue = 1,
                maxValue = 65535
            )
        )
        self.parameterDefinition('MAX_REFLECTANCE').setHelp('Default to 10000 for Sentinel 2-L2A.\n Ignore if using Drone Orthomosaics.')
        self.addParameter(
             QgsProcessingParameterEnum(
                'SPLIT_METHOD',
                self.tr('Split Method'),
                options=['Random', 'Spatial'],
                defaultValue=1
            )
        )
        

        self.addParameter(
            QgsProcessingParameterNumber(
                'VAL_SPLIT',
                self.tr('Validation Split (%)'),
                type = QgsProcessingParameterNumber.Integer,
                defaultValue = 20,
                minValue = 1,
                maxValue = 50
            )
        )
        
        self.addParameter(
             QgsProcessingParameterEnum(
                'TRAINING_ENV',
                self.tr('Training Environment'),
                options=['Kaggle', 'Google Colab', 'Local'],
                defaultValue=2
            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                'OUTPUT_FOLDER',
                self.tr('Output Folder'),
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
    #---Read Parameters---
        feedback.pushInfo('Algorithm started')

        extent = self.parameterAsExtent(parameters, 'MAP_EXTENT', context)

        raster = self.parameterAsRasterLayer(parameters, 'INPUT_RASTER', context)

        vector = self.parameterAsVectorLayer(parameters, 'INPUT_VECTOR', context)

        class_field = self.parameterAsString(parameters, 'CLASS_FIELD', context)

        chip_size = self.parameterAsInt(parameters, 'CHIP_SIZE', context)

        task = self.parameterAsInt(parameters, 'TASK', context)
        
        overlap = self.parameterAsInt(parameters, 'OVERLAP', context)
        step = int(chip_size * (1 - overlap / 100))
        
        data_source = self.parameterAsInt(parameters, 'DATA_SOURCE', context)

        max_reflectance = self.parameterAsInt(parameters, 'MAX_REFLECTANCE', context)

        split_method = self.parameterAsInt(parameters, 'SPLIT_METHOD', context)

        val_split = self.parameterAsInt(parameters, 'VAL_SPLIT', context)

        training_env = self.parameterAsInt(parameters, 'TRAINING_ENV', context)

        output_folder = self.parameterAsString(parameters, 'OUTPUT_FOLDER', context)

        #Folder Structure
        train_img = os.path.join(output_folder, 'images', 'train')
        val_img = os.path.join(output_folder, 'images', 'val')
        train_mask = os.path.join(output_folder, 'labels', 'train')
        val_mask = os.path.join(output_folder, 'labels', 'val')
        for folder in [train_img, val_img, train_mask, val_mask]: 
            os.makedirs(folder, exist_ok = True)

        feedback.pushInfo('____________Pre-Processing:___________')

        #Clip Raster to Extent
        feedback.pushInfo('Clipping Raster to Extent')
        clipped_raster = QgsProcessingUtils.generateTempFilename('clipped_raster.tif')
        processing.run('gdal:cliprasterbyextent', {'INPUT': raster,
                                                   'PROJWIN': extent,
                                                   'OVERCRS': False,
                                                   'OUTPUT': clipped_raster
                                                   }
                                                )

        #Reproject Vector if CRS not the same as Raster
        feedback.pushInfo('Reprojecting Vector')
        result = processing.run('native:reprojectlayer', 
                                {'INPUT': vector, 
                                'TARGET_CRS': raster.crs(), 
                                'OUTPUT': 'memory:'
                                }
                                )
        vector = result['OUTPUT']

        #Class Get Features
        unique_classes = set()
        for feature in vector.getFeatures():
            value = feature[class_field]
            if value is not None:
                unique_classes.add(value)
        
        CLASS_MAP = {name: idx for idx, name in enumerate(sorted(unique_classes), start=0)}
        
        #Class label assignment
        feedback.pushInfo('Classing Label')
        vector.startEditing()

        if vector.fields().indexOf('class_id') == -1:
            vector.addAttribute(QgsField('class_id', QVariant.Int))  
            vector.updateFields()
            
        for feature in vector.getFeatures():
            class_value = feature[class_field]
            class_id = CLASS_MAP.get(class_value, 0)
            vector.changeAttributeValue(feature.id(), vector.fields().indexOf('class_id'), class_id)
        
        vector.commitChanges()
        vector.dataProvider().updateExtents()
        vector.dataProvider().createSpatialIndex()

    #---Chipping---
        feedback.pushInfo('____________Processing:___________')
        feedback.pushInfo('Chipping')
        gdal_raster = gdal.Open(clipped_raster)

        gt = gdal_raster.GetGeoTransform()
        
        raster_width = gdal_raster.RasterXSize
        raster_height = gdal_raster.RasterYSize

        n_cols = math.ceil((raster_width - chip_size) / step) + 1
        n_rows = math.ceil((raster_height - chip_size) / step) + 1

        mem_driver = gdal.GetDriverByName('MEM')
        png_driver = gdal.GetDriverByName('PNG')

        val_row_cutoff = int(n_rows * (1 - val_split / 100))

        total_chips = n_rows * n_cols
        chips_done = 0
        
        for row in range(n_rows):
            for col in range(n_cols):
                if feedback.isCanceled():
                    return{}

                #Clamping images
                x_off = min(col * step, raster_width - chip_size)
                y_off = min(row * step, raster_height - chip_size)
                
                chip_x_min = gt[0] + x_off * gt[1]
                chip_y_max = gt[3] + y_off * gt[5]
                chip_x_max = gt[0] + (x_off + chip_size) * gt[1]
                chip_y_min = gt[3] + (y_off + chip_size) * gt[5]

                chip_extent = QgsRectangle(chip_x_min, chip_y_min, chip_x_max, chip_y_max)
                request = QgsFeatureRequest().setFilterRect(chip_extent)

                raster_data = gdal_raster.ReadAsArray(x_off, y_off, chip_size, chip_size)

                #---Output---
                if split_method == 1:
                    if row >= val_row_cutoff:
                        img_out = val_img
                        mask_out = val_mask
                    else:
                        img_out = train_img
                        mask_out = train_mask
                else:
                    if random.random() < val_split / 100:
                        img_out = val_img
                        mask_out = val_mask
                    else:
                        img_out = train_img
                        mask_out = train_mask
                    
                image_path = os.path.join(img_out, f'image_{row:04d}_{col:04d}.png')
                mask_path = os.path.join(mask_out, f'image_{row:04d}_{col:04d}.txt')

                if data_source == 0: 
                    raster_data = np.clip(raster_data / max_reflectance * 255, 0, 255).astype(np.uint8)
                else:
                    raster_data = np.clip(raster_data, 0, 255).astype(np.uint8)

                ##Image Chip
                tmp_img_ds = mem_driver.Create('', chip_size, chip_size, raster_data.shape[0], gdal.GDT_Byte)
                for band in range(raster_data.shape[0]):
                    tmp_img_ds.GetRasterBand(band + 1).WriteArray(raster_data[band])
                png_driver.CreateCopy(image_path, tmp_img_ds)
                tmp_img_ds = None

                ##Mask Chip
                with open(mask_path, 'w') as f:
                    if task == 0:
                        for feature in vector.getFeatures(request):
                            class_id = feature['class_id']
                            bbox = feature.geometry().boundingBox()

                            px_min = (bbox.xMinimum() - gt[0]) / gt[1]
                            py_min = (bbox.yMaximum() - gt[3]) / gt[5]
                            px_max = (bbox.xMaximum() - gt[0]) / gt[1]
                            py_max = (bbox.yMinimum() - gt[3]) / gt[5]

                            rx_min = max(0, (px_min - x_off) / chip_size)
                            ry_min = max(0, (py_min - y_off) / chip_size)
                            rx_max = min(1, (px_max - x_off) / chip_size)
                            ry_max = min(1, (py_max - y_off) / chip_size)

                            x_center = (rx_min + rx_max) / 2
                            y_center = (ry_min + ry_max) / 2
                            w_norm = rx_max - rx_min
                            h_norm = ry_max - ry_min

                            if w_norm < 0.01 or h_norm < 0.01:
                                continue

                            f.write(f'{int(class_id)} {x_center:.6f} {y_center:.6f} {w_norm:.6f} {h_norm:.6f}\n')
                    else: 
                        blank = np.zeros((chip_size, chip_size), dtype=np.uint8)
                        for feature in vector.getFeatures(request):
                            class_id = feature['class_id']
                            geom = feature.geometry()

                            if geom.isMultipart():
                                polygons = geom.asMultiPolygon()

                            else:
                                polygons = [geom.asPolygon()]

                            for polygon in polygons:
                                for ring in polygon:
                                    pts = []
                                    for point in ring:
                                        px = int((point.x() - gt[0]) / gt[1] - x_off)
                                        py = int((point.y() - gt[3]) / gt[5] - y_off)
                                        pts.append([px, py])
                                    pts = np.array(pts, dtype = np.int32)
                                    cv2.fillPoly(blank, [pts], color=int(class_id) + 1)

                        for class_id in np.unique(blank):
                            if class_id == 0:
                                continue
                            binary = np.where(blank == class_id, 255, 0).astype(np.uint8)
                            contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[-2:]
                            for contour in contours:
                                if len(contour) < 3:
                                    continue
                                normalized = contour.reshape(-1, 2) / chip_size
                                flat = normalized.flatten()
                                coords = ' '.join(f'{v:.6f}' for v in flat)
                                f.write(f'{int(class_id) - 1} {coords}\n')
                                                            
                chips_done += 1
                feedback.setProgress(int((chips_done / total_chips) * 100))

        #Generate classes.txt
        classes_path = os.path.join(output_folder, 'classes.txt')
        with open(classes_path, 'w') as f:
            for name in sorted(CLASS_MAP, key = lambda x: CLASS_MAP[x]):
                f.write(name + '\n')

        #Generate YAML (Based on Training Environment)
        feedback.pushInfo('Generating data.yaml')
        def create_data_yaml():
            
            if training_env == 0:
                path_to_output = '/kaggle/working/data'
            elif training_env == 1:
                path_to_output = '/content/data'
            else:
                path_to_output = output_folder
                
            classes = sorted(CLASS_MAP, key=lambda x: CLASS_MAP[x])
            number_of_classes = len(classes)

            data = {
                'path': path_to_output,
                'train': 'images/train',
                'val': 'images/val',
                'nc': number_of_classes,
                'names': classes
            }

            with open(os.path.join(output_folder, 'data.yaml'), 'w') as f:
                yaml.dump(data, f, sort_keys=False)

            return
        
        create_data_yaml()
        
        feedback.pushInfo(f'Total Chips: {total_chips}')
        feedback.pushInfo(f'Training dataset saved to: {output_folder}')
        
        #File handle cleanup
        gdal_raster = None

        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Chip Images'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Image'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return VecToYOLOAlgorithm()
