# -*- coding: utf-8 -*-

"""
/***************************************************************************
 VecToYOLO
                                 A QGIS plugin
 This plugin generates image chips for YOLO training
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        copyright            : (C) 2026 by Yogi Satrio Wijoyo
        email                : s.wyogi32@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yogi Satrio Wijoyo'
__date__ = '2026-03-02'
__copyright__ = '(C) 2026 by Yogi Satrio Wijoyo'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .vec_to_yolo_provider import VecToYOLOProvider
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from .rectangle_map_tool import RectangleMapTool

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class VecToYOLOPlugin(object):

    def __init__(self, iface):
        self.iface = iface
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = VecToYOLOProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        self.toolbar = self.iface.addToolBar('VecToYOLO')
        self.map_tool = RectangleMapTool(self.iface.mapCanvas())
        icon = QIcon(os.path.join(cmd_folder, 'icon.png'))
        self.action = QAction(icon, 'Draw Annotation Rectangle', self.iface.mainWindow())
        self.action.setCheckable(True)
        self.action.triggered.connect(self.activate_map_tool)
        self.toolbar.addAction(self.action)

    def activate_map_tool(self):
        self.iface.mapCanvas().setMapTool(self.map_tool)
    
    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        del self.toolbar
